services:
  int-proxy:
    build: .
    image: caddy-acme-dns
    container_name: int-proxy
    read_only: true
    restart: unless-stopped
    env_file:
      - ${SECRETS_DIR:?}/int-proxy/.env
    environment:
      MY_DOMAIN: "${MY_DOMAIN:?}"
    ports:
      - "80:80"
      - "443:443/tcp"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      net-pihole:
        ipv4_address: 172.19.1.2
      net-int-homepage:
        ipv4_address: 172.19.4.2
      outgoing:
        ipv4_address: 172.19.0.2
    labels:
      homepage.group: "Internal"
      homepage.name: "Caddy Reverse Proxy"
      homepage.icon: "caddy.png"
      homepage.description: "Reverse proxy for internal services."

volumes:
  caddy_data:
  caddy_config:

networks:
  net-pihole:
    external: true
  net-int-homepage:
    external: true
  outgoing:
    ipam:
      config:
        - subnet: 172.19.0.0/24
          gateway: 172.19.0.1
