services:
  int-proxy:
    build: .
    image: int-caddy
    container_name: int-proxy
    user: 190:190
    read_only: true
    restart: unless-stopped
    env_file:
      - ${SECRETS_DIR:?}/int-proxy/.env
    environment:
      MY_DOMAIN: "${MY_DOMAIN:?}"
      PROXMOX_IP: "${PROXMOX_IP:?}"
    ports:
      - "${INT_PROXY_IP:?}:80:80"
      - "${INT_PROXY_IP:?}:443:443/tcp"
      - "${INT_PROXY_IP:?}:443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ../utils/caddy:/etc/caddy/caddy-configs:ro
      - ${CONFIGS_DIR:?}/error-pages/dist:/srv/error-pages:ro
      - caddy-data:/data
      - caddy-config:/config
    networks:
      prom-int-caddy:
        ipv4_address: 172.21.3.3
      net-int-homepage:
        ipv4_address: 172.19.2.2
      net-pihole:
        ipv4_address: 172.19.3.2
      net-grafana:
        ipv4_address: 172.19.6.2
      outgoing:
        ipv4_address: 172.19.0.130
    labels:
      homepage.group: "Internal"
      homepage.name: "Caddy Reverse Proxy"
      homepage.icon: "caddy.png"
      homepage.description: "Reverse proxy for internal services."

volumes:
  caddy-data:
  caddy-config:

networks:
  prom-int-caddy:
    external: true
  net-int-homepage:
    external: true
  net-pihole:
    external: true
  net-grafana:
    external: true
  outgoing:
    ipam:
      config:
        - subnet: 172.19.0.0/24
          gateway: 172.19.0.129
