services:
  internal-proxy:
    build: .
    image: caddy-acme-dns
    container_name: internal-proxy
    read_only: true
    restart: unless-stopped
    env_file:
      - ${SECRETS_DIR:?}/internal-proxy/.env
    environment:
      MY_DOMAIN: "${MY_DOMAIN:?}"
    ports:
      - "80:80"
      - "443:443/tcp"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      outgoing:
        ipv4_address: 172.19.0.2
      net-pihole:
        ipv4_address: 172.19.1.2
      net-homepage:
        ipv4_address: 172.19.4.2

volumes:
  caddy_data:
  caddy_config:

networks:
  net-pihole:
    external: true
  net-homepage:
    external: true
  outgoing:
    ipam:
      config:
        - subnet: "172.19.0.0/24"
          gateway: "172.19.0.1"
