services:
  prometheus:
    image: prom/prometheus:v3.3.0
    container_name: prometheus
    read_only: true
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - data:/prometheus
    networks:
      prom-wg:
        ipv4_address: 172.21.1.2
      prom-ext-caddy:
        ipv4_address: 172.21.2.2
      prom-int-caddy:
        ipv4_address: 172.21.3.2
      prom-authentik:
        ipv4_address: 172.21.4.2
      prom-grafana:
        ipv4_address: 172.21.5.2
      prom-cadvisor:
        ipv4_address: 172.21.6.2
      prom-node-exporter:
        ipv4_address: 172.21.7.2
    labels:
      homepage.group: "Monitoring"
      homepage.name: "Prometheus"
      homepage.icon: "prometheus.png"
      homepage.description: "Monitoring system and time series database."
      homepage.weight: "2"

volumes:
  data:

networks:
  prom-wg:
    external: true
  prom-ext-caddy:
    external: true
  prom-int-caddy:
    external: true
  prom-authentik:
    external: true
  prom-grafana:
    external: true
  prom-cadvisor:
    external: true
  prom-node-exporter:
    external: true
