services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.52.1
    container_name: cadvisor
    read_only: true
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /run/rootlesskit/docker.socket:/var/run/docker.sock:ro
      - /sys:/sys:ro
      - /home/dockeruser/.local/share/docker:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      prom-cadvisor:
        ipv4_address: 172.21.6.3

  node-exporter:
    image: quay.io/prometheus/node-exporter:v1.9.1
    container_name: node-exporter
    read_only: true
    restart: unless-stopped
    pid: "host"
    volumes:
      - /:/host:ro,rslave
    networks:
      prom-node-exporter:
        ipv4_address: 172.21.7.3
    command:
      - "--path.rootfs=/host"

networks:
  prom-cadvisor:
    external: true
  prom-node-exporter:
    external: true
