services:
  pihole:
    image: pihole/pihole:2025.04.0
    container_name: pihole
    restart: unless-stopped
    environment:
      TZ: "Europe/Zurich"
      FTLCONF_webserver_api_password: "${PIHOLE_API_PASSWORD:?error}"
      FTLCONF_dns_listeningMode: "all"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - "${SERVICES_DIR:?error}/pihole/etc-pihole:/etc/pihole"
    networks:
      outgoing:
        ipv4_address: 172.19.53.2
      net-pihole:
        ipv4_address: 172.19.1.4

networks:
  net-pihole:
    external: true
  outgoing:
    ipam:
      config:
        - subnet: "172.19.53.0/24"
          gateway: "172.19.53.1"
