services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    environment:
      TZ: "Europe/Zurich"
      FTLCONF_webserver_api_password: ""
      FTLCONF_dns_listeningMode: "all"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - "${SERVICES_DIR:?error}/pihole/etc-pihole:/etc/pihole"
    networks:
      - net-pihole
      - default

networks:
  net-pihole:
    external: true
