services:
  pihole:
    image: pihole/pihole:2025.04.0
    container_name: pihole
    restart: unless-stopped
    environment:
      TZ: "Europe/Zurich"
      FTLCONF_webserver_api_password: "${PIHOLE_API_PASSWORD:?error}"
      FTLCONF_dns_listeningMode: "all"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - "${SERVICES_DIR:?error}/pihole/etc-pihole:/etc/pihole"
    networks:
      net-pihole:
        ipv4_address: 172.19.0.3

networks:
  net-pihole:
    external: true
