services:
  pihole:
    image: pihole/pihole:2025.04.0
    container_name: pihole
    restart: unless-stopped
    environment:
      TZ: "Europe/Zurich"
      FTLCONF_webserver_api_password: ""
      FTLCONF_dns_listeningMode: "all"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - "${SERVICES_DIR:?error}/pihole/etc-pihole:/etc/pihole"
    networks:
      net-pihole:
        ipv4_address: 172.19.1.3
      default:
        ipv4_address: 172.20.0.2

networks:
  net-pihole:
    external: true
  default:
    ipam:
      config:
        - subnet: "172.20.0.0/24"
          gateway: "172.20.0.1"
