services:
  pihole:
    image: pihole/pihole:2025.04.0
    container_name: pihole
    restart: unless-stopped
    environment:
      TZ: "Europe/Zurich"
      FTLCONF_webserver_api_password: "${PIHOLE_PASSWORD:?}"
      FTLCONF_dns_listeningMode: "all"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - config:/etc/pihole
    networks:
      net-pihole:
        ipv4_address: 172.19.3.4
      outgoing:
        ipv4_address: 172.19.3.130
    labels:
      homepage.group: "Internal"
      homepage.name: "Pi-hole"
      homepage.icon: "pi-hole.png"
      homepage.instance.internal.href: "https://pihole.${MY_DOMAIN:?}"
      homepage.description: "Network-wide ad blocker."
      homepage.instance.internal.widget.type: "pihole"
      homepage.instance.internal.widget.url: "https://pihole.${MY_DOMAIN:?}"
      homepage.instance.internal.widget.version: "6"
      homepage.instance.internal.widget.key: "${PIHOLE_PASSWORD:?}"

volumes:
  config:

networks:
  net-pihole:
    external: true
  outgoing:
    ipam:
      config:
        - subnet: 172.19.3.128/25
          gateway: 172.19.3.129
