services:
  postgresql:
    image: docker.io/library/postgres:16-alpine
    container_name: authentik-postgresql
    read_only: true
    restart: unless-stopped
    env_file:
      - ${SECRETS_DIR:?}/authentik/.env-postgresql
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      internal:
        ipv4_address: 172.18.4.66
    tmpfs:
      - /var/run/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s

  redis:
    image: docker.io/library/redis:8-alpine
    container_name: authentik-redis
    read_only: true
    restart: unless-stopped
    volumes:
      - redis:/data
    networks:
      internal:
        ipv4_address: 172.18.4.67
    command: --save 60 1 --loglevel warning
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s

  server:
    image: ghcr.io/goauthentik/server:2025.4.1
    command: server
    container_name: authentik-server
    read_only: true
    restart: unless-stopped
    env_file:
      - ${SECRETS_DIR:?}/authentik/.env-authentik
    volumes:
      - writable:/media
      - ${CONFIGS_DIR:?}/media/images/background-image.jpg:/media/background-image.jpg:ro
      - templates:/templates
    networks:
      prom-authentik:
        ipv4_address: 172.21.4.3
      net-ext-authentik:
        ipv4_address: 172.18.4.4
      net-int-authentik:
        ipv4_address: 172.19.7.4
      internal:
        ipv4_address: 172.18.4.68
      outgoing:
        ipv4_address: 172.18.4.130
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy
    labels:
      homepage.group: "External"
      homepage.name: "Authentik"
      homepage.icon: "authentik.png"
      homepage.href: "https://auth.${MY_DOMAIN:?}"
      homepage.description: "A self-hosted SSO and identity provider."

  worker:
    image: ghcr.io/goauthentik/server:2025.4.1
    command: worker
    container_name: authentik-worker
    read_only: true
    restart: unless-stopped
    env_file:
      - ${SECRETS_DIR:?}/authentik/.env-authentik
    volumes:
      - writable:/media
      - ${CONFIGS_DIR:?}/media/images/background-image.jpg:/media/background-image.jpg
      - templates:/templates
    networks:
      internal:
        ipv4_address: 172.18.4.69
      outgoing:
        ipv4_address: 172.18.4.131
    tmpfs:
      - /certs
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  database:
  redis:
  templates:
  writable:

networks:
  prom-authentik:
    external: true
  net-ext-authentik:
    external: true
  net-int-authentik:
    external: true
  internal:
    internal: true
    ipam:
      config:
        - subnet: 172.18.4.64/26
          gateway: 172.18.4.65
  outgoing:
    ipam:
      config:
        - subnet: 172.18.4.128/26
          gateway: 172.18.4.129
