services:
  radarr:
    image: ghcr.io/hotio/radarr:release-6.0.4.10291
    container_name: radarr
    # user: 2187:65537 # set below
    # read_only: true # doesn't work otherwise
    restart: unless-stopped
    depends_on:
      - int-postgresql
      - prowlarr
      - qui
    environment:
      PUID: "2187"
      PGID: "65537" # host's `media` <-> container's 65537
      UMASK: "002"
      TZ: "Europe/Zurich"
    volumes:
      - ${SLOW_VOLUMES:?}/media-server/radarr/config:/config
      - ${STORAGE_DIR:?}/media-server:/data
    networks:
      net-int-media:
        ipv4_address: 172.19.8.4
      seerr-radarr:
        ipv4_address: 172.19.8.34
      radarr-out:
        ipv4_address: 172.19.8.130
    labels:
      alloy.enable_logging: "true"
      homepage.group: "Media"
      homepage.name: "Radarr"
      homepage.icon: "radarr.png"
      homepage.instance.internal.href: "https://radarr.${MY_DOMAIN:?}"
      homepage.description: "Radarr is a movie collection manager for Usenet and BitTorrent users."
      homepage.instance.internal.widget.type: "radarr"
      homepage.instance.internal.widget.url: "https://radarr.${MY_DOMAIN:?}"
      homepage.instance.internal.widget.key: "${INT_HOMEPAGE_RADARR_API_KEY:?}"
      homepage.instance.internal.widget.username: "${INT_HOMEPAGE_AUTHENTIK_USERNAME:?}"
      homepage.instance.internal.widget.password: "${INT_HOMEPAGE_AUTHENTIK_PASSWORD:?}"
      homepage.weight: "200"

networks:
  radarr-out:
    ipam:
      config:
        - subnet: 172.19.8.128/30
          gateway: 172.19.8.129
