services:
  scraparr:
    image: ghcr.io/thecfu/scraparr:2.2.5
    container_name: scraparr
    user: 14187:14187
    read_only: true
    restart: unless-stopped
    depends_on:
      - radarr
      - sonarr
      - bazarr
      - prowlarr
      - seerr
    env_file:
      - ${SECRETS_DIR:?}/media-server/scraparr/.env
    environment:
      GENERAL_ADDRESS: "172.21.12.3"
      RADARR_URL: "http://radarr:7878"
      SONARR_URL: "http://sonarr:8989"
      BAZARR_URL: "http://bazarr:6767"
      PROWLARR_URL: "http://prowlarr:9696"
      JELLYSEERR_URL: "http://seerr:5055"
    networks:
      prom-scraparr:
        ipv4_address: 172.21.12.3
      net-int-media:
        ipv4_address: 172.19.8.12
      seerr-scraparr:
        ipv4_address: 172.19.8.50
    labels:
      alloy.enable_logging: "true"
      homepage.group: "Monitoring"
      homepage.name: "Scraparr"
      homepage.icon: "sh-scraparr.png"
      homepage.description: "Scraparr is a Prometheus exporter for the *arr stack."
      homepage.weight: "800"

networks:
  prom-scraparr:
    external: true
