services:
  int-homepage:
    image: gethomepage/homepage:v1.1.1
    container_name: int-homepage
    restart: unless-stopped
    environment:
      HOMEPAGE_ALLOWED_HOSTS: "home.${MY_DOMAIN:?}"
      LOG_TARGETS: "stdout"
    volumes:
      - ${CONFIGS_DIR:?}/int-homepage/config:/app/config
      - ${CONFIGS_DIR:?}/int-homepage/public/images:/app/public/images
      - ${CONFIGS_DIR:?}/int-homepage/public/icons:/app/public/icons
    networks:
      net-int-homepage:
        ipv4_address: 172.19.4.4
      internal:
        ipv4_address: 172.21.4.3
      outgoing:
        ipv4_address: 172.19.251.2
    labels:
      homepage.group: "Internal"
      homepage.name: "Internal Homepage"
      homepage.icon: "homepage.png"
      homepage.instance.internal.href: "https://home.${MY_DOMAIN:?}"
      homepage.instance.internal.description: "This very homepage!"
      homepage.instance.external.description: "A hidden homepage... displaying even more services!"

  int-dockerproxy:
    image: tecnativa/docker-socket-proxy:0.3
    container_name: int-dockerproxy
    restart: unless-stopped
    environment:
      CONTAINERS: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      internal:
        ipv4_address: 172.21.4.2

networks:
  net-int-homepage:
    external: true
  outgoing:
    ipam:
      config:
        - subnet: 172.19.251.0/24
          gateway: 172.19.251.1
  internal:
    internal: true
    ipam:
      config:
        - subnet: 172.21.4.0/24
          gateway: 172.21.4.1
