services:
  int-homepage:
    image: gethomepage/homepage:v1.1.1
    container_name: int-homepage
    read_only: true
    restart: unless-stopped
    depends_on:
      - int-dockerproxy
    environment:
      HOMEPAGE_ALLOWED_HOSTS: "home.${MY_DOMAIN:?}"
      LOG_TARGETS: "stdout"
    volumes:
      - ${CONFIGS_DIR:?}/int-homepage/config:/app/config:ro
      - ${CONFIGS_DIR:?}/int-homepage/public/images:/app/public/images:ro
      - ${CONFIGS_DIR:?}/int-homepage/public/icons:/app/public/icons:ro
      - writable:/app/.next/server/pages
    networks:
      net-int-homepage:
        ipv4_address: 172.19.2.4
      internal:
        ipv4_address: 172.19.2.66
      outgoing:
        ipv4_address: 172.19.2.130
    labels:
      homepage.group: "Internal"
      homepage.name: "Internal Homepage"
      homepage.icon: "homepage.png"
      homepage.instance.internal.href: "https://home.${MY_DOMAIN:?}"
      homepage.instance.internal.description: "This very homepage!"
      homepage.instance.external.description: "A hidden homepage... displaying more details about every service!"

  int-dockerproxy:
    image: tecnativa/docker-socket-proxy:0.3
    container_name: int-dockerproxy
    restart: unless-stopped
    environment:
      CONTAINERS: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      internal:
        ipv4_address: 172.19.2.67

volumes:
  writable:

networks:
  net-int-homepage:
    external: true
  internal:
    internal: true
    ipam:
      config:
        - subnet: 172.19.2.64/26
          gateway: 172.19.2.65
  outgoing:
    ipam:
      config:
        - subnet: 172.19.2.128/26
          gateway: 172.19.2.129
