services:
  int-homepage:
    build: ${SERVICES_DIR:?}/homepage
    image: homepage
    container_name: int-homepage
    user: 1192:1192
    read_only: true
    restart: unless-stopped
    depends_on:
      - int-dockerproxy
    environment:
      PUID: "1192"
      PGID: "1192"
      HOMEPAGE_ALLOWED_HOSTS: "home.${MY_DOMAIN:?}"
      LOG_TARGETS: "stdout"
    volumes:
      - ${CONFIGS_DIR:?}/int-homepage/config:/app/config:ro
      - ${CONFIGS_DIR:?}/webmedia/images/background-image.jpg:/app/public/images/background-image.jpg:ro
      - ${CONFIGS_DIR:?}/webmedia/icons/dabloon.png:/app/public/icons/dabloon.png:ro
      - ${CONFIGS_DIR:?}/webmedia/icons/homepage-favicon.ico:/app/public/favicon.ico:ro
      - ${CONFIGS_DIR:?}/webmedia/icons/homepage-favicon.ico:/app/public/favicon-32x32.png:ro
      - writable:/app/.next/server/pages
    networks:
      net-int-homepage:
        ipv4_address: 172.19.2.4
      internal:
        ipv4_address: 172.19.2.66
      outgoing:
        ipv4_address: 172.19.2.130
    labels:
      homepage.group: "Internal"
      homepage.name: "Internal Homepage"
      homepage.icon: "homepage.png"
      homepage.instance.internal.href: "https://${MY_DOMAIN:?}"
      homepage.instance.internal.description: "This very homepage!"
      homepage.instance.external.description: "A hidden homepage... displaying more details about every service!"

  int-dockerproxy:
    image: tecnativa/docker-socket-proxy:0.3
    container_name: int-dockerproxy
    restart: unless-stopped
    environment:
      CONTAINERS: 1
    volumes:
      - /run/rootlesskit/docker.socket:/var/run/docker.sock:ro
    networks:
      internal:
        ipv4_address: 172.19.2.67

volumes:
  writable:

networks:
  net-int-homepage:
    external: true
  internal:
    internal: true
    ipam:
      config:
        - subnet: 172.19.2.64/26
          gateway: 172.19.2.65
  outgoing:
    ipam:
      config:
        - subnet: 172.19.2.128/26
          gateway: 172.19.2.129
