global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'wireguard'
    static_configs:
      - targets: ['wireguard:9586']

  - job_name: 'ext-proxy'
    static_configs:
      - targets: ['ext-proxy:2019']

  - job_name: 'int-proxy'
    static_configs:
      - targets: ['int-proxy:2019']

  - job_name: 'authentik'
    static_configs:
      - targets: ['authentik-server:9300']
