services:
  ext-tele-bot:
    build: ${SERVICES_DIR:?}/telegram-bot
    image: telegram-bot
    container_name: ext-tele-bot
    read_only: true
    restart: unless-stopped
    env_file:
      - ${SECRETS_DIR:?}/telegram-bot/.env
    networks:
      ext-outgoing:
        ipv4_address: 172.18.255.2
      net-dabloon:
        ipv4_address: 172.18.1.3

  int-tele-bot:
    build: ${SERVICES_DIR:?}/telegram-bot
    image: telegram-bot
    container_name: int-tele-bot
    read_only: true
    restart: unless-stopped
    env_file:
      - ${SECRETS_DIR:?}/telegram-bot/.env
    networks:
      int-outgoing:
        ipv4_address: 172.19.255.2
      net-pihole:
        ipv4_address: 172.19.1.3
      net-ddclient:
        ipv4_address: 172.19.2.3
      net-fw-monitor:
        ipv4_address: 172.19.3.3

networks:
  net-dabloon:
    external: true
  net-pihole:
    external: true
  net-ddclient:
    external: true
  net-fw-monitor:
    external: true
  ext-outgoing:
    ipam:
      config:
        - subnet: "172.18.255.0/24"
          gateway: "172.18.255.1"
  int-outgoing:
    ipam:
      config:
        - subnet: "172.19.255.0/24"
          gateway: "172.19.255.1"
