services:
  ext-tele-bot:
    build: ${SERVICES_DIR:?error}/telegram-bot
    image: telegram-bot
    container_name: ext-tele-bot
    read_only: true
    restart: unless-stopped
    env_file:
      - ${SECRETS_DIR:?error}/telegram-bot/.env
    networks:
      net-dabloon:
        ipv4_address: 172.18.1.3

  int-tele-bot:
    build: ${SERVICES_DIR:?error}/telegram-bot
    image: telegram-bot
    container_name: int-tele-bot
    read_only: true
    restart: unless-stopped
    env_file:
      - ${SECRETS_DIR:?error}/telegram-bot/.env
    networks:
      net-pihole:
        ipv4_address: 172.19.1.3

networks:
  net-dabloon:
    external: true
  net-pihole:
    external: true
