services:
  ext-tele-bot:
    build: ${SERVICES_DIR:?}/telegram-bot
    image: telegram-bot
    container_name: ext-tele-bot
    read_only: true
    restart: unless-stopped
    env_file:
      - ${SECRETS_DIR:?}/telegram-bot/.env
    networks:
      net-dabloon:
        ipv4_address: 172.18.3.3
      ext-outgoing:
        ipv4_address: 172.18.1.130
    labels:
      homepage.group: "External"
      homepage.name: "Telegram Bot"
      homepage.icon: "telegram.png"
      homepage.instance.internal.href: "${CHAT_INVITE_LINK:?}"
      homepage.description: "Telegram bot for external services."

  int-tele-bot:
    build: ${SERVICES_DIR:?}/telegram-bot
    image: telegram-bot
    container_name: int-tele-bot
    read_only: true
    restart: unless-stopped
    env_file:
      - ${SECRETS_DIR:?}/telegram-bot/.env
    networks:
      net-pihole:
        ipv4_address: 172.19.3.3
      net-ddclient:
        ipv4_address: 172.19.4.3
      net-fw-monitor:
        ipv4_address: 172.19.5.3
      int-outgoing:
        ipv4_address: 172.19.1.130
    labels:
      homepage.group: "Internal"
      homepage.name: "Telegram Bot"
      homepage.icon: "telegram.png"
      homepage.instance.internal.href: "${CHAT_INVITE_LINK:?}"
      homepage.description: "Telegram bot for internal services."

networks:
  net-dabloon:
    external: true
  net-pihole:
    external: true
  net-ddclient:
    external: true
  net-fw-monitor:
    external: true
  ext-outgoing:
    ipam:
      config:
        - subnet: 172.18.1.0/24
          gateway: 172.18.1.129
  int-outgoing:
    ipam:
      config:
        - subnet: 172.19.1.0/24
          gateway: 172.19.1.129
