services:
  ext-proxy:
    build: .
    image: ext-caddy
    container_name: ext-proxy
    read_only: true
    restart: unless-stopped
    environment:
      MY_DOMAIN: "${MY_DOMAIN:?}"
    ports:
      - "8080:80"
      - "8443:443/tcp"
      - "8443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ../utils/caddy:/etc/caddy/caddy-configs:ro
      - ${CONFIGS_DIR:?}/error-pages/dist:/srv/error-pages:ro
      - caddy-data:/data
      - caddy-config:/config
    networks:
      prom-ext-caddy:
        ipv4_address: 172.21.2.3
      net-ext-homepage:
        ipv4_address: 172.18.2.2
      net-dabloon:
        ipv4_address: 172.18.3.2
      net-authentik:
        ipv4_address: 172.18.4.2
      outgoing:
        ipv4_address: 172.18.0.130
    labels:
      homepage.group: "External"
      homepage.name: "Caddy Reverse Proxy"
      homepage.icon: "caddy.png"
      homepage.description: "Reverse proxy for external services."

volumes:
  caddy-data:
  caddy-config:

networks:
  prom-ext-caddy:
    external: true
  net-ext-homepage:
    external: true
  net-dabloon:
    external: true
  net-authentik:
    external: true
  outgoing:
    ipam:
      config:
        - subnet: 172.18.0.0/24
          gateway: 172.18.0.129
