services:
  dabloon:
    build: ${SERVICES_DIR:?error}/dabloon-clicker
    image: dabloon-clicker
    container_name: dabloon
    read_only: true
    restart: unless-stopped
    env_file:
      - ${SECRETS_DIR:?error}/dabloon-clicker/.env
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - dabloon-clicker

volumes:
  caddy_data:
  caddy_config:

networks:
  dabloon-clicker:
    external: true
