services:
  dabloon:
    build: ${SERVICES_DIR:?}/dabloon-clicker
    image: dabloon-clicker
    container_name: dabloon
    read_only: true
    restart: unless-stopped
    env_file:
      - ${SECRETS_DIR:?}/dabloon-clicker/.env
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      net-dabloon:
        ipv4_address: 172.18.3.4
    labels:
      homepage.group: "External"
      homepage.name: "Dabloon Clicker"
      homepage.icon: "/icons/dabloon.png"
      homepage.href: "https://dabloon.${MY_DOMAIN:?}"
      homepage.description: "Click on dabloons to win even more dabloons!"

volumes:
  caddy_data:
  caddy_config:

networks:
  net-dabloon:
    external: true
