services:
  ddclient:
    build:
      context: .
      args:
        MY_DOMAIN: "${MY_DOMAIN:?}"
    image: ddclient
    container_name: ddclient
    user: 194:194
    read_only: true
    restart: unless-stopped
    env_file:
      - ${SECRETS_DIR:?}/ddclient/.env
    environment:
      TZ: "Europe/Zurich"
    networks:
      net-ddclient:
        ipv4_address: 172.19.4.4
      outgoing:
        ipv4_address: 172.19.4.130
    tmpfs:
      - /run:exec
      - /tmp
    labels:
      homepage.group: "Internal"
      homepage.name: "DDClient"
      homepage.icon: "ddclient.png"
      homepage.instance.internal.href: "${DDNS_HOMEPAGE_URL:?}"
      homepage.description: "Update DNS records dynamically."

networks:
  net-ddclient:
    external: true
  outgoing:
    ipam:
      config:
        - subnet: 172.19.4.128/25
          gateway: 172.19.4.129
