services:
  wireguard:
    image: linuxserver/wireguard:1.0.20210914
    container_name: wireguard
    read_only: true
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      TZ: "Europe/Zurich"
      SERVERURL: "vpn.${MY_DOMAIN:?}"
      SERVERPORT: "51820"
      PEERS: "flip6,hpkali,hpwindows,themachine,deniseiphone,deniseasus"
    ports:
      - "51820:51820/udp"
    volumes:
      - ${CONFIGS_DIR:?}/wireguard/config:/config
    networks:
      outgoing:
        ipv4_address: 172.20.0.2
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
    tmpfs:
      - /run:exec
    labels:
      homepage.group: "External"
      homepage.name: "WireGuard"
      homepage.icon: "wireguard.png"
      homepage.description: "Connect home safe!"

networks:
  outgoing:
    ipam:
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1
