services:
  wireguard:
    image: linuxserver/wireguard:1.0.20210914
    container_name: wireguard
    read_only: true
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      TZ: "Europe/Zurich"
      SERVERURL: "vpn.${MY_DOMAIN:?}"
      SERVERPORT: "51820"
      PEERS: "flip6,hpkali,hpwindows,themachine,deniseiphone,deniseasus"
    ports:
      - "51820:51820/udp"
    volumes:
      - ${CONFIGS_DIR:?}/wireguard/config:/config
    networks:
      prom-wg:
        ipv4_address: 172.21.1.3
      outgoing:
        ipv4_address: 172.20.0.130
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
    tmpfs:
      - /run:exec
    labels:
      homepage.group: "External"
      homepage.name: "WireGuard"
      homepage.icon: "wireguard.png"
      homepage.description: "Connect home safe!"

  wireguard-exporter:
    image: mindflavor/prometheus-wireguard-exporter:3.6.6
    container_name: wireguard-exporter
    read_only: true
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    user: root
    environment:
      PROMETHEUS_WIREGUARD_EXPORTER_ADDRESS: "172.19.7.3"
      PROMETHEUS_WIREGUARD_EXPORTER_CONFIG_FILE_NAMES: "/config/wg_confs/wg0.conf"
      EXPORT_LATEST_HANDSHAKE_DELAY: "true"
    volumes:
      - ${CONFIGS_DIR:?}/wireguard/config:/config:ro
    command: "-a false"
    network_mode: "service:wireguard"
    labels:
      homepage.group: "Monitoring"
      homepage.name: "WireGuard Monitoring"
      homepage.icon: "wireguard.png"
      homepage.description: "Monitor WireGuard connections."
      homepage.weight: "6"

networks:
  prom-wg:
    external: true
  outgoing:
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.129
