services:
  wireguard:
    image: linuxserver/wireguard:1.0.20250521
    container_name: wireguard
    user: 0:0 # required
    read_only: true
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      # PUID: "911" # default user of linuxserver images, nonmodifiable because read_only: true
      # PGID: "1001" # default user of linuxserver images, nonmodifiable because read_only: true
      TZ: "Europe/Zurich"
      SERVERURL: "vpn.${MY_DOMAIN:?}"
      SERVERPORT: "51820"
      PEERS: "${WIREGUARD_PEERS:?}"
    ports:
      - "${VPN_IP:?}:51820:51820/udp"
    volumes:
      - ${SLOW_VOLUMES:?}/wireguard/config:/config:ro
    networks:
      prom-wg:
        ipv4_address: 172.21.1.3
      outgoing:
        ipv4_address: 172.20.0.130
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
      net.ipv4.ip_forward: 1
    tmpfs:
      - /run:exec
    labels:
      homepage.group: "External"
      homepage.name: "WireGuard"
      homepage.icon: "wireguard.png"
      homepage.description: "Connect home safe!"

  wireguard-exporter:
    image: mindflavor/prometheus-wireguard-exporter:3.6.6
    container_name: wireguard-exporter
    user: 0:0 # required to be the same user as wireguard to read the config file
    read_only: true
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      PROMETHEUS_WIREGUARD_EXPORTER_ADDRESS: "172.21.1.3"
      PROMETHEUS_WIREGUARD_EXPORTER_CONFIG_FILE_NAMES: "/config/wg_confs/wg0.conf"
      EXPORT_LATEST_HANDSHAKE_DELAY: "true"
    volumes:
      - ${SLOW_VOLUMES:?}/wireguard/config/wg_confs/wg0.conf:/config/wg_confs/wg0.conf:ro
    command: "-a false"
    network_mode: "service:wireguard"

networks:
  prom-wg:
    external: true
  outgoing:
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.129
