services:
  wireguard:
    image: linuxserver/wireguard:1.0.20210914
    container_name: wireguard
    read_only: true
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      - TZ=Europe/Zurich
      - SERVERURL=vpn.pierugo.ch
      - SERVERPORT=51820
      - PEERS=flip6,hpkali,hpwindows,themachine,deniseiphone,deniseasus
    ports:
      - "51820:51820/udp"
    volumes:
      - ${SERVICES_DIR:?error}/wireguard/config:/config
    networks:
      default:
        ipv4_address: 172.20.0.2
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    tmpfs:
      - /run:exec

networks:
  default:
    ipam:
      config:
        - subnet: "172.20.0.0/24"
          gateway: "172.20.0.1"
